version = 1

test_patterns = ["test_*.py"]

exclude_patterns = [
  "qodana.yaml",
  "gui.tcss"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"
