name: Discord Notifications

on: [push]

jobs:
  github-notify-to-discord:
    runs-on: ubuntu-latest
    steps:
        - name: Discord Commits
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            include-extras: true
        - name: Test Info
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: info
            details: Test succeeded.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Test Warn
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: warn
            details: Test warning.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Test Error
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: error
            details: Test failed.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
